import type { PokemonProfile, PowerStone } from '../types';
import { DEFAULT_PRIORITY_ORDER } from '../constants/stats';

export const INITIAL_POKEMON: PokemonProfile[] = [
  {
    id: 'poke-bulbasaur-01',
    pokedexId: 1,
    name: 'Vine Whip Bulbasaur',
    level: 100,
    priorities: [
      'HIT_HEAL',
      'CRIT_RATE',
      'CRIT_DMG',
      'STATUS_RESIST',
      'STAT_LOWER_RESIST',
      'MOVE_SPEED',
      'TIME_TO_RECOVER',
      'NATURAL_HEAL',
      'HP_UPON_RECOVERY',
    ],
    sockets: [
      { slotIndex: 0, type: 'ATK', isUnlocked: true },
      { slotIndex: 1, type: 'HP', isUnlocked: true },
      { slotIndex: 2, type: 'ATK', isUnlocked: true },
      { slotIndex: 3, type: 'HP', isUnlocked: true },
      { slotIndex: 4, type: 'MULTI', isUnlocked: true },
      { slotIndex: 5, type: 'ATK', isUnlocked: true },
      { slotIndex: 6, type: 'ATK', isUnlocked: true },
      { slotIndex: 7, type: 'HP', isUnlocked: true },
      { slotIndex: 8, type: 'ATK', isUnlocked: true },
    ],
  },
  {
    id: 'poke-onix-02',
    pokedexId: 95,
    name: 'Rock Throw Onix',
    level: 100,
    priorities: [
      'HIT_HEAL',
      'CRIT_RATE',
      'CRIT_DMG',
      'STATUS_RESIST',
      'STAT_LOWER_RESIST',
      'MOVE_SPEED',
      'TIME_TO_RECOVER',
      'NATURAL_HEAL',
      'HP_UPON_RECOVERY',
    ],
    sockets: [
      { slotIndex: 0, type: 'ATK', isUnlocked: true },
      { slotIndex: 1, type: 'ATK', isUnlocked: true },
      { slotIndex: 2, type: 'HP', isUnlocked: true },
      { slotIndex: 3, type: 'ATK', isUnlocked: true },
      { slotIndex: 4, type: 'MULTI', isUnlocked: true },
      { slotIndex: 5, type: 'ATK', isUnlocked: true },
      { slotIndex: 6, type: 'HP', isUnlocked: true },
      { slotIndex: 7, type: 'ATK', isUnlocked: true },
      { slotIndex: 8, type: 'ATK', isUnlocked: true },
    ],
  },
  {
    id: 'poke-machop-03',
    pokedexId: 66,
    name: 'Bulk Up Machop',
    level: 100,
    priorities: DEFAULT_PRIORITY_ORDER,
    sockets: [
      { slotIndex: 0, type: 'ATK', isUnlocked: true },
      { slotIndex: 1, type: 'HP', isUnlocked: true },
      { slotIndex: 2, type: 'HP', isUnlocked: true },
      { slotIndex: 3, type: 'MULTI', isUnlocked: true },
      { slotIndex: 4, type: 'ATK', isUnlocked: true },
      { slotIndex: 5, type: 'ATK', isUnlocked: true },
      { slotIndex: 6, type: 'HP', isUnlocked: true },
      { slotIndex: 7, type: 'HP', isUnlocked: true },
      { slotIndex: 8, type: 'ATK', isUnlocked: true },
    ],
  },
];

export const INITIAL_STONES: PowerStone[] = [
  // Equipped to Bulbasaur (poke-bulbasaur-01)
  {
    id: 'stone-001',
    type: 'ATK',
    power: 980,
    subStats: [
      { type: 'HIT_HEAL', value: 2.8 },
      { type: 'CRIT_RATE', value: 18.4 },
      { type: 'CRIT_DMG', value: 22.1 },
    ],
    isLocked: true,
    assignedPokemonId: 'poke-bulbasaur-01',
    assignedSlotIndex: 0,
  },
  {
    id: 'stone-002',
    type: 'HP',
    power: 895,
    subStats: [
      { type: 'STATUS_RESIST', value: 25.0 },
      { type: 'STAT_LOWER_RESIST', value: 24.0 },
      { type: 'HIT_HEAL', value: 2.5 },
    ],
    isLocked: true,
    assignedPokemonId: 'poke-bulbasaur-01',
    assignedSlotIndex: 1,
  },
  {
    id: 'stone-003',
    type: 'ATK',
    power: 955,
    subStats: [
      { type: 'HIT_HEAL', value: 2.9 },
      { type: 'MOVE_SPEED', value: 28.0 },
    ],
    isLocked: false,
    assignedPokemonId: 'poke-bulbasaur-01',
    assignedSlotIndex: 2,
  },
  {
    id: 'stone-004',
    type: 'HP',
    power: 910,
    subStats: [
      { type: 'HIT_HEAL', value: 1.8 },
      { type: 'STAT_LOWER_RESIST', value: 28.5 },
    ],
    isLocked: false,
    assignedPokemonId: 'poke-bulbasaur-01',
    assignedSlotIndex: 3,
  },
  {
    id: 'stone-005',
    type: 'HP',
    power: 990,
    subStats: [
      { type: 'STATUS_RESIST', value: 30.0 },
      { type: 'NATURAL_HEAL', value: 45.0 },
    ],
    isLocked: true,
    assignedPokemonId: 'poke-bulbasaur-01',
    assignedSlotIndex: 4,
  },
  {
    id: 'stone-006',
    type: 'ATK',
    power: 940,
    subStats: [
      { type: 'CRIT_RATE', value: 24.5 },
      { type: 'CRIT_DMG', value: 25.0 },
    ],
    isLocked: false,
    assignedPokemonId: 'poke-bulbasaur-01',
    assignedSlotIndex: 5,
  },
  {
    id: 'stone-007',
    type: 'ATK',
    power: 925,
    subStats: [
      { type: 'STATUS_RESIST', value: 20.0 },
      { type: 'MOVE_SPEED', value: 32.0 },
    ],
    isLocked: false,
    assignedPokemonId: 'poke-bulbasaur-01',
    assignedSlotIndex: 6,
  },

  // Loose Stones in Inventory
  {
    id: 'stone-101',
    type: 'ATK',
    power: 998,
    subStats: [
      { type: 'HIT_HEAL', value: 2.9 },
      { type: 'CRIT_RATE', value: 28.0 },
      { type: 'CRIT_DMG', value: 29.5 },
    ],
    isLocked: true,
    assignedPokemonId: null,
    assignedSlotIndex: null,
  },
  {
    id: 'stone-102',
    type: 'HP',
    power: 975,
    subStats: [
      { type: 'HIT_HEAL', value: 2.7 },
      { type: 'STATUS_RESIST', value: 26.0 },
    ],
    isLocked: false,
    assignedPokemonId: null,
    assignedSlotIndex: null,
  },
  {
    id: 'stone-103',
    type: 'ATK',
    power: 960,
    subStats: [
      { type: 'CRIT_RATE', value: 22.0 },
      { type: 'MOVE_SPEED', value: 40.0 },
    ],
    isLocked: false,
    assignedPokemonId: null,
    assignedSlotIndex: null,
  },
  {
    id: 'stone-104',
    type: 'HP',
    power: 920,
    subStats: [
      { type: 'TIME_TO_RECOVER', value: 18.0 },
      { type: 'HP_UPON_RECOVERY', value: 16.5 },
    ],
    isLocked: false,
    assignedPokemonId: null,
    assignedSlotIndex: null,
  },
  {
    id: 'stone-105',
    type: 'ATK',
    power: 935,
    subStats: [
      { type: 'HIT_HEAL', value: 2.1 },
      { type: 'HEAL_FROM_KO', value: 1.8 },
      { type: 'NATURAL_HEAL', value: 50.0 },
    ],
    isLocked: false,
    assignedPokemonId: null,
    assignedSlotIndex: null,
  },
  {
    id: 'stone-106',
    type: 'HP',
    power: 880,
    subStats: [
      { type: 'STATUS_RESIST', value: 22.0 },
      { type: 'MOVE_SPEED', value: 25.0 },
    ],
    isLocked: false,
    assignedPokemonId: null,
    assignedSlotIndex: null,
  },
  {
    id: 'stone-107',
    type: 'ATK',
    power: 850,
    subStats: [
      { type: 'CRIT_DMG', value: 20.0 },
    ],
    isLocked: false,
    assignedPokemonId: null,
    assignedSlotIndex: null,
  },
  {
    id: 'stone-108',
    type: 'HP',
    power: 890,
    subStats: [
      { type: 'HIT_HEAL', value: 2.3 },
      { type: 'TIME_TO_RECOVER', value: 12.0 },
    ],
    isLocked: false,
    assignedPokemonId: null,
    assignedSlotIndex: null,
  },
  {
    id: 'stone-109',
    type: 'ATK',
    power: 999,
    subStats: [],
    isLocked: false,
    assignedPokemonId: null,
    assignedSlotIndex: null,
  },
];
