export interface PokemonSpecies {
  id: number;
  name: string;
  type: string;
  primaryColor: string;
  secondaryColor?: string;
}

export interface PokemonTypeMeta {
  bg: string;
  text: string;
  border: string;
  badgeClass?: string;
}

export const POKEMON_TYPE_COLORS: Record<string, PokemonTypeMeta> = {
  Normal:   { bg: '#A8A878', text: '#FFFFFF', border: '#8A8A59' },
  Fire:     { bg: '#F08030', text: '#FFFFFF', border: '#C05810' },
  Water:    { bg: '#6890F0', text: '#FFFFFF', border: '#386CEB' },
  Grass:    { bg: '#78C850', text: '#FFFFFF', border: '#4E9C26' },
  Electric: { bg: '#F8D030', text: '#1E2124', border: '#D0A810' },
  Ice:      { bg: '#98D8D8', text: '#1E2124', border: '#60B8B8' },
  Fighting: { bg: '#C03028', text: '#FFFFFF', border: '#901E18' },
  Poison:   { bg: '#A040A0', text: '#FFFFFF', border: '#782078' },
  Ground:   { bg: '#E0C068', text: '#1E2124', border: '#B89838' },
  Flying:   { bg: '#A890F0', text: '#FFFFFF', border: '#7860D0' },
  Psychic:  { bg: '#F85888', text: '#FFFFFF', border: '#D02858' },
  Bug:      { bg: '#A8B820', text: '#FFFFFF', border: '#788810' },
  Rock:     { bg: '#B8A038', text: '#FFFFFF', border: '#887018' },
  Ghost:    { bg: '#705898', text: '#FFFFFF', border: '#483070' },
  Dragon:   { bg: '#7038F8', text: '#FFFFFF', border: '#4010D0' },
  Steel:    { bg: '#B8B8D0', text: '#1E2124', border: '#8888A8' },
  Fairy:    { bg: '#EE99AC', text: '#1E2124', border: '#C8687E' },
};

export const GEN1_POKEDEX: PokemonSpecies[] = [
  { id: 1, name: "Bulbasaur", type: "Grass", primaryColor: "#78C850" },
  { id: 2, name: "Ivysaur", type: "Grass", primaryColor: "#78C850" },
  { id: 3, name: "Venusaur", type: "Grass", primaryColor: "#78C850" },
  { id: 4, name: "Charmander", type: "Fire", primaryColor: "#F08030" },
  { id: 5, name: "Charmeleon", type: "Fire", primaryColor: "#F08030" },
  { id: 6, name: "Charizard", type: "Fire", primaryColor: "#F08030" },
  { id: 7, name: "Squirtle", type: "Water", primaryColor: "#6890F0" },
  { id: 8, name: "Wartortle", type: "Water", primaryColor: "#6890F0" },
  { id: 9, name: "Blastoise", type: "Water", primaryColor: "#6890F0" },
  { id: 10, name: "Caterpie", type: "Bug", primaryColor: "#A8B820" },
  { id: 11, name: "Metapod", type: "Bug", primaryColor: "#A8B820" },
  { id: 12, name: "Butterfree", type: "Bug", primaryColor: "#A8B820" },
  { id: 13, name: "Weedle", type: "Bug", primaryColor: "#A8B820" },
  { id: 14, name: "Kakuna", type: "Bug", primaryColor: "#A8B820" },
  { id: 15, name: "Beedrill", type: "Bug", primaryColor: "#A8B820" },
  { id: 16, name: "Pidgey", type: "Normal", primaryColor: "#A8A878" },
  { id: 17, name: "Pidgeotto", type: "Normal", primaryColor: "#A8A878" },
  { id: 18, name: "Pidgeot", type: "Normal", primaryColor: "#A8A878" },
  { id: 19, name: "Rattata", type: "Normal", primaryColor: "#A8A878" },
  { id: 20, name: "Raticate", type: "Normal", primaryColor: "#A8A878" },
  { id: 21, name: "Spearow", type: "Normal", primaryColor: "#A8A878" },
  { id: 22, name: "Fearow", type: "Normal", primaryColor: "#A8A878" },
  { id: 23, name: "Ekans", type: "Poison", primaryColor: "#A040A0" },
  { id: 24, name: "Arbok", type: "Poison", primaryColor: "#A040A0" },
  { id: 25, name: "Pikachu", type: "Electric", primaryColor: "#F8D030" },
  { id: 26, name: "Raichu", type: "Electric", primaryColor: "#F8D030" },
  { id: 27, name: "Sandshrew", type: "Ground", primaryColor: "#E0C068" },
  { id: 28, name: "Sandslash", type: "Ground", primaryColor: "#E0C068" },
  { id: 29, name: "Nidoran♀", type: "Poison", primaryColor: "#A040A0" },
  { id: 30, name: "Nidorina", type: "Poison", primaryColor: "#A040A0" },
  { id: 31, name: "Nidoqueen", type: "Poison", primaryColor: "#A040A0" },
  { id: 32, name: "Nidoran♂", type: "Poison", primaryColor: "#A040A0" },
  { id: 33, name: "Nidorino", type: "Poison", primaryColor: "#A040A0" },
  { id: 34, name: "Nidoking", type: "Poison", primaryColor: "#A040A0" },
  { id: 35, name: "Clefairy", type: "Fairy", primaryColor: "#EE99AC" },
  { id: 36, name: "Clefable", type: "Fairy", primaryColor: "#EE99AC" },
  { id: 37, name: "Vulpix", type: "Fire", primaryColor: "#F08030" },
  { id: 38, name: "Ninetales", type: "Fire", primaryColor: "#F08030" },
  { id: 39, name: "Jigglypuff", type: "Normal", primaryColor: "#A8A878" },
  { id: 40, name: "Wigglytuff", type: "Normal", primaryColor: "#A8A878" },
  { id: 41, name: "Zubat", type: "Poison", primaryColor: "#A040A0" },
  { id: 42, name: "Golbat", type: "Poison", primaryColor: "#A040A0" },
  { id: 43, name: "Oddish", type: "Grass", primaryColor: "#78C850" },
  { id: 44, name: "Gloom", type: "Grass", primaryColor: "#78C850" },
  { id: 45, name: "Vileplume", type: "Grass", primaryColor: "#78C850" },
  { id: 46, name: "Paras", type: "Bug", primaryColor: "#A8B820" },
  { id: 47, name: "Parasect", type: "Bug", primaryColor: "#A8B820" },
  { id: 48, name: "Venonat", type: "Bug", primaryColor: "#A8B820" },
  { id: 49, name: "Venomoth", type: "Bug", primaryColor: "#A8B820" },
  { id: 50, name: "Diglett", type: "Ground", primaryColor: "#E0C068" },
  { id: 51, name: "Dugtrio", type: "Ground", primaryColor: "#E0C068" },
  { id: 52, name: "Meowth", type: "Normal", primaryColor: "#A8A878" },
  { id: 53, name: "Persian", type: "Normal", primaryColor: "#A8A878" },
  { id: 54, name: "Psyduck", type: "Water", primaryColor: "#6890F0" },
  { id: 55, name: "Golduck", type: "Water", primaryColor: "#6890F0" },
  { id: 56, name: "Mankey", type: "Fighting", primaryColor: "#C03028" },
  { id: 57, name: "Primeape", type: "Fighting", primaryColor: "#C03028" },
  { id: 58, name: "Growlithe", type: "Fire", primaryColor: "#F08030" },
  { id: 59, name: "Arcanine", type: "Fire", primaryColor: "#F08030" },
  { id: 60, name: "Poliwag", type: "Water", primaryColor: "#6890F0" },
  { id: 61, name: "Poliwhirl", type: "Water", primaryColor: "#6890F0" },
  { id: 62, name: "Poliwrath", type: "Water", primaryColor: "#6890F0" },
  { id: 63, name: "Abra", type: "Psychic", primaryColor: "#F85888" },
  { id: 64, name: "Kadabra", type: "Psychic", primaryColor: "#F85888" },
  { id: 65, name: "Alakazam", type: "Psychic", primaryColor: "#F85888" },
  { id: 66, name: "Machop", type: "Fighting", primaryColor: "#C03028" },
  { id: 67, name: "Machoke", type: "Fighting", primaryColor: "#C03028" },
  { id: 68, name: "Machamp", type: "Fighting", primaryColor: "#C03028" },
  { id: 69, name: "Bellsprout", type: "Grass", primaryColor: "#78C850" },
  { id: 70, name: "Weepinbell", type: "Grass", primaryColor: "#78C850" },
  { id: 71, name: "Victreebel", type: "Grass", primaryColor: "#78C850" },
  { id: 72, name: "Tentacool", type: "Water", primaryColor: "#6890F0" },
  { id: 73, name: "Tentacruel", type: "Water", primaryColor: "#6890F0" },
  { id: 74, name: "Geodude", type: "Rock", primaryColor: "#B8A038" },
  { id: 75, name: "Graveler", type: "Rock", primaryColor: "#B8A038" },
  { id: 76, name: "Golem", type: "Rock", primaryColor: "#B8A038" },
  { id: 77, name: "Ponyta", type: "Fire", primaryColor: "#F08030" },
  { id: 78, name: "Rapidash", type: "Fire", primaryColor: "#F08030" },
  { id: 79, name: "Slowpoke", type: "Water", primaryColor: "#6890F0" },
  { id: 80, name: "Slowbro", type: "Water", primaryColor: "#6890F0" },
  { id: 81, name: "Magnemite", type: "Electric", primaryColor: "#F8D030" },
  { id: 82, name: "Magneton", type: "Electric", primaryColor: "#F8D030" },
  { id: 83, name: "Farfetch'd", type: "Normal", primaryColor: "#A8A878" },
  { id: 84, name: "Doduo", type: "Normal", primaryColor: "#A8A878" },
  { id: 85, name: "Dodrio", type: "Normal", primaryColor: "#A8A878" },
  { id: 86, name: "Seel", type: "Water", primaryColor: "#6890F0" },
  { id: 87, name: "Dewgong", type: "Water", primaryColor: "#6890F0" },
  { id: 88, name: "Grimer", type: "Poison", primaryColor: "#A040A0" },
  { id: 89, name: "Muk", type: "Poison", primaryColor: "#A040A0" },
  { id: 90, name: "Shellder", type: "Water", primaryColor: "#6890F0" },
  { id: 91, name: "Cloyster", type: "Water", primaryColor: "#6890F0" },
  { id: 92, name: "Gastly", type: "Ghost", primaryColor: "#705898" },
  { id: 93, name: "Haunter", type: "Ghost", primaryColor: "#705898" },
  { id: 94, name: "Gengar", type: "Ghost", primaryColor: "#705898" },
  { id: 95, name: "Onix", type: "Rock", primaryColor: "#B8A038" },
  { id: 96, name: "Drowzee", type: "Psychic", primaryColor: "#F85888" },
  { id: 97, name: "Hypno", type: "Psychic", primaryColor: "#F85888" },
  { id: 98, name: "Krabby", type: "Water", primaryColor: "#6890F0" },
  { id: 99, name: "Kingler", type: "Water", primaryColor: "#6890F0" },
  { id: 100, name: "Voltorb", type: "Electric", primaryColor: "#F8D030" },
  { id: 101, name: "Electrode", type: "Electric", primaryColor: "#F8D030" },
  { id: 102, name: "Exeggcute", type: "Grass", primaryColor: "#78C850" },
  { id: 103, name: "Exeggutor", type: "Grass", primaryColor: "#78C850" },
  { id: 104, name: "Cubone", type: "Ground", primaryColor: "#E0C068" },
  { id: 105, name: "Marowak", type: "Ground", primaryColor: "#E0C068" },
  { id: 106, name: "Hitmonlee", type: "Fighting", primaryColor: "#C03028" },
  { id: 107, name: "Hitmonchan", type: "Fighting", primaryColor: "#C03028" },
  { id: 108, name: "Lickitung", type: "Normal", primaryColor: "#A8A878" },
  { id: 109, name: "Koffing", type: "Poison", primaryColor: "#A040A0" },
  { id: 110, name: "Weezing", type: "Poison", primaryColor: "#A040A0" },
  { id: 111, name: "Rhyhorn", type: "Ground", primaryColor: "#E0C068" },
  { id: 112, name: "Rhydon", type: "Ground", primaryColor: "#E0C068" },
  { id: 113, name: "Chansey", type: "Normal", primaryColor: "#A8A878" },
  { id: 114, name: "Tangela", type: "Grass", primaryColor: "#78C850" },
  { id: 115, name: "Kangaskhan", type: "Normal", primaryColor: "#A8A878" },
  { id: 116, name: "Horsea", type: "Water", primaryColor: "#6890F0" },
  { id: 117, name: "Seadra", type: "Water", primaryColor: "#6890F0" },
  { id: 118, name: "Goldeen", type: "Water", primaryColor: "#6890F0" },
  { id: 119, name: "Seaking", type: "Water", primaryColor: "#6890F0" },
  { id: 120, name: "Staryu", type: "Water", primaryColor: "#6890F0" },
  { id: 121, name: "Starmie", type: "Water", primaryColor: "#6890F0" },
  { id: 122, name: "Mr. Mime", type: "Psychic", primaryColor: "#F85888" },
  { id: 123, name: "Scyther", type: "Bug", primaryColor: "#A8B820" },
  { id: 124, name: "Jynx", type: "Ice", primaryColor: "#98D8D8" },
  { id: 125, name: "Electabuzz", type: "Electric", primaryColor: "#F8D030" },
  { id: 126, name: "Magmar", type: "Fire", primaryColor: "#F08030" },
  { id: 127, name: "Pinsir", type: "Bug", primaryColor: "#A8B820" },
  { id: 128, name: "Tauros", type: "Normal", primaryColor: "#A8A878" },
  { id: 129, name: "Magikarp", type: "Water", primaryColor: "#6890F0" },
  { id: 130, name: "Gyarados", type: "Water", primaryColor: "#6890F0" },
  { id: 131, name: "Lapras", type: "Water", primaryColor: "#6890F0" },
  { id: 132, name: "Ditto", type: "Normal", primaryColor: "#A8A878" },
  { id: 133, name: "Eevee", type: "Normal", primaryColor: "#A8A878" },
  { id: 134, name: "Vaporeon", type: "Water", primaryColor: "#6890F0" },
  { id: 135, name: "Jolteon", type: "Electric", primaryColor: "#F8D030" },
  { id: 136, name: "Flareon", type: "Fire", primaryColor: "#F08030" },
  { id: 137, name: "Porygon", type: "Normal", primaryColor: "#A8A878" },
  { id: 138, name: "Omanyte", type: "Rock", primaryColor: "#B8A038" },
  { id: 139, name: "Omastar", type: "Rock", primaryColor: "#B8A038" },
  { id: 140, name: "Kabuto", type: "Rock", primaryColor: "#B8A038" },
  { id: 141, name: "Kabutops", type: "Rock", primaryColor: "#B8A038" },
  { id: 142, name: "Aerodactyl", type: "Rock", primaryColor: "#B8A038" },
  { id: 143, name: "Snorlax", type: "Normal", primaryColor: "#A8A878" },
  { id: 144, name: "Articuno", type: "Ice", primaryColor: "#98D8D8" },
  { id: 145, name: "Zapdos", type: "Electric", primaryColor: "#F8D030" },
  { id: 146, name: "Moltres", type: "Fire", primaryColor: "#F08030" },
  { id: 147, name: "Dratini", type: "Dragon", primaryColor: "#7038F8" },
  { id: 148, name: "Dragonair", type: "Dragon", primaryColor: "#7038F8" },
  { id: 149, name: "Dragonite", type: "Dragon", primaryColor: "#7038F8" },
  { id: 150, name: "Mewtwo", type: "Psychic", primaryColor: "#F85888" },
  { id: 151, name: "Mew", type: "Psychic", primaryColor: "#F85888" },
];

export const getPokemonById = (id: number): PokemonSpecies => {
  return GEN1_POKEDEX.find(p => p.id === id) || {
    id,
    name: `Pokémon #${id}`,
    type: "Normal",
    primaryColor: "#A8A878",
  };
};

export const formatPokedexNumber = (id: number): string => {
  return `#${id.toString().padStart(3, '0')}`;
};
